//
//  TranscriptFetcher.swift
//  Straight Up Browser
//
//  YouTube caption ingestion (Phase 2, design §8.1): captions are read the way
//  the player itself gets them — the caption-track list from the video page's
//  own player response, then the track's json3 payload from YouTube's caption
//  endpoint. Captions only, no ASR, no audio download; a video with captions
//  disabled simply has no transcript.
//

import Foundation
import WebKit

@MainActor
final class TranscriptFetcher {
    private let ledgerStore: LedgerStore
    /// Source keys with a fetch in flight, so settle + panel-open don't race.
    private var inFlight: Set<String> = []

    init(ledgerStore: LedgerStore) {
        self.ledgerStore = ledgerStore
    }

    /// One caption track as the player response lists it.
    nonisolated struct CaptionTrack: Codable, Equatable, Sendable {
        let baseUrl: String
        let languageCode: String
        /// "asr" marks YouTube's auto-generated track.
        let kind: String?

        var isAutoGenerated: Bool { kind == "asr" }
    }

    /// Existing transcript, or fetch-and-store. Returns nil when the source has
    /// no captions, the page isn't a video, or the fetch failed (no row is
    /// written on failure — the transcript panel offers Retry).
    @discardableResult
    func ensureTranscript(for article: NewspaperArticle, webView: WKWebView?) async -> SourceTranscript? {
        if let existing = ledgerStore.transcript(sourceKey: article.sourceKey) { return existing }
        guard article.modality == .video, let webView else { return nil }
        guard !inFlight.contains(article.sourceKey) else { return nil }
        inFlight.insert(article.sourceKey)
        defer { inFlight.remove(article.sourceKey) }

        guard let tracks = await captionTracks(from: webView), !tracks.isEmpty,
              let track = Self.chooseTrack(tracks, preferredLanguages: Locale.preferredLanguages),
              let url = Self.json3URL(for: track)
        else { return nil }

        guard let (data, _) = try? await URLSession.shared.data(from: url) else { return nil }
        let segments = Self.parseJSON3(data)
        guard !segments.isEmpty else { return nil }

        return ledgerStore.storeTranscript(
            sourceId: article.id,
            sourceKey: article.sourceKey,
            languageCode: track.languageCode,
            isAutoGenerated: track.isAutoGenerated,
            segments: segments
        )
    }

    /// The track list, read from the live page. Primary source is the initial
    /// player response; no scraping of markup, no third-party endpoint.
    private func captionTracks(from webView: WKWebView) async -> [CaptionTrack]? {
        let js = """
        (() => {
          try {
            const t = (window.ytInitialPlayerResponse || {}).captions
              ?.playerCaptionsTracklistRenderer?.captionTracks;
            return t ? JSON.stringify(t) : null;
          } catch (e) { return null; }
        })()
        """
        guard let result = try? await webView.evaluateJavaScript(js),
              let json = result as? String
        else { return nil }
        return Self.parseCaptionTracks(Data(json.utf8))
    }

    // MARK: Pure parsing (unit-tested directly)

    nonisolated static func parseCaptionTracks(_ data: Data) -> [CaptionTrack]? {
        try? JSONDecoder().decode([CaptionTrack].self, from: data)
    }

    /// Manual captions beat auto-generated; the user's language beats the
    /// video's default; the first listed track is the video's own default.
    nonisolated static func chooseTrack(
        _ tracks: [CaptionTrack],
        preferredLanguages: [String]
    ) -> CaptionTrack? {
        guard !tracks.isEmpty else { return nil }
        let preferredCodes = preferredLanguages.map {
            $0.components(separatedBy: "-").first?.lowercased() ?? $0.lowercased()
        }
        func languageRank(_ track: CaptionTrack) -> Int {
            let code = track.languageCode.components(separatedBy: "-").first?.lowercased() ?? ""
            return preferredCodes.firstIndex(of: code) ?? Int.max
        }
        return tracks.enumerated().min { a, b in
            if a.element.isAutoGenerated != b.element.isAutoGenerated {
                return !a.element.isAutoGenerated
            }
            if languageRank(a.element) != languageRank(b.element) {
                return languageRank(a.element) < languageRank(b.element)
            }
            return a.offset < b.offset
        }?.element
    }

    nonisolated static func json3URL(for track: CaptionTrack) -> URL? {
        guard var components = URLComponents(string: track.baseUrl) else { return nil }
        var items = components.queryItems ?? []
        items.removeAll { $0.name == "fmt" }
        items.append(URLQueryItem(name: "fmt", value: "json3"))
        components.queryItems = items
        return components.url
    }

    /// YouTube's json3 shape: { events: [ { tStartMs, dDurationMs, segs: [ { utf8 } ] } ] }.
    nonisolated static func parseJSON3(_ data: Data) -> [TranscriptSegment] {
        struct Payload: Codable {
            struct Event: Codable {
                struct Seg: Codable { let utf8: String? }
                let tStartMs: Double?
                let dDurationMs: Double?
                let segs: [Seg]?
            }
            let events: [Event]?
        }
        guard let payload = try? JSONDecoder().decode(Payload.self, from: data) else { return [] }
        return (payload.events ?? []).compactMap { event in
            guard let start = event.tStartMs, let segs = event.segs else { return nil }
            let text = segs.compactMap(\.utf8).joined()
                .replacingOccurrences(of: "\n", with: " ")
                .trimmingCharacters(in: .whitespacesAndNewlines)
            guard !text.isEmpty else { return nil }
            return TranscriptSegment(s: start / 1000, d: (event.dDurationMs ?? 0) / 1000, t: text)
        }
    }

    // MARK: Search

    /// Case-insensitive substring search across stored transcripts, for the
    /// omnibar's cross-transcript rows. Returns at most `limit` hits, one per
    /// video. ponytail: linear scan over decoded blobs on each query — cached
    /// nowhere; add a rebuildable index if profiling ever demands one.
    nonisolated struct TranscriptHit: Equatable, Sendable {
        let sourceKey: String
        let segment: TranscriptSegment
    }

    func search(_ query: String, limit: Int = 2) -> [TranscriptHit] {
        let needle = query.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        guard needle.count >= 3 else { return [] }
        var hits: [TranscriptHit] = []
        for transcript in ledgerStore.allTranscripts() {
            if let segment = transcript.segments.first(where: { $0.t.lowercased().contains(needle) }) {
                hits.append(TranscriptHit(sourceKey: transcript.sourceKey, segment: segment))
                if hits.count >= limit { break }
            }
        }
        return hits
    }
}
