#!/bin/bash
#
# Builds, signs, notarizes, and staples a distributable Browser.dmg.
#
# One-time setup:
#   1. Create a "Developer ID Application" certificate:
#      Xcode -> Settings -> Accounts -> Manage Certificates -> + -> Developer ID Application
#   2. Store notarization credentials (app-specific password from account.apple.com):
#      xcrun notarytool store-credentials notary --apple-id nathanfennel@gmail.com --team-id EJLR2RPSV2
#
# Usage: ./scripts/release.sh          (override profile with NOTARY_PROFILE=name)
# Output: build/release/Browser.dmg — upload this to the website.

set -euo pipefail
cd "$(dirname "$0")/.."

PROJECT="Straight Up Browser.xcodeproj"
SCHEME="Browser"
PROFILE="${NOTARY_PROFILE:-notary}"
BUILD="build/release"

security find-identity -v -p codesigning | grep -q "Developer ID Application" || {
    echo "No 'Developer ID Application' certificate in the keychain."
    echo "Create one: Xcode -> Settings -> Accounts -> Manage Certificates -> + -> Developer ID Application"
    exit 1
}

# The scheme is Xcode-autogenerated (no shared .xcscheme on disk) - verify it resolves
xcodebuild -list -project "$PROJECT" 2>/dev/null | grep -q "^        $SCHEME\$" || {
    echo "Scheme '$SCHEME' not found. Open the project in Xcode once to autogenerate it."
    exit 1
}

rm -rf "$BUILD"
mkdir -p "$BUILD"

xcodebuild archive -project "$PROJECT" -scheme "$SCHEME" -configuration Release \
    -archivePath "$BUILD/Browser.xcarchive" -allowProvisioningUpdates

cat > "$BUILD/exportOptions.plist" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
    <key>method</key><string>developer-id</string>
    <key>teamID</key><string>EJLR2RPSV2</string>
    <key>signingStyle</key><string>automatic</string>
</dict></plist>
EOF

xcodebuild -exportArchive -archivePath "$BUILD/Browser.xcarchive" \
    -exportOptionsPlist "$BUILD/exportOptions.plist" -exportPath "$BUILD/export" \
    -allowProvisioningUpdates

STAGE="$BUILD/dmg"
DMG="$BUILD/Browser.dmg"
mkdir -p "$STAGE"
cp -R "$BUILD/export/Browser.app" "$STAGE/"
ln -s /Applications "$STAGE/Applications"

# Notarize and staple the app itself before it goes into the DMG, so a
# first launch works offline; the DMG gets its own ticket below.
ditto -c -k --keepParent "$STAGE/Browser.app" "$BUILD/Browser.zip"
xcrun notarytool submit "$BUILD/Browser.zip" --keychain-profile "$PROFILE" --wait
xcrun stapler staple "$STAGE/Browser.app"

hdiutil create -volname "Browser" -srcfolder "$STAGE" -ov -format UDZO "$DMG"

codesign --force --sign "Developer ID Application" "$DMG"
xcrun notarytool submit "$DMG" --keychain-profile "$PROFILE" --wait
xcrun stapler staple "$DMG"
spctl -a -t open --context context:primary-signature -v "$DMG"

# Sparkle appcast: reads the version out of the stapled DMG and signs it with
# the EdDSA private key in this Mac's Keychain (scripts/sparkle-bin/generate_keys
# put it there — see DEPLOYMENT.md). $BUILD holds only this release's DMG, so
# the feed always describes just the latest version (no delta patches).
# Browser.zip was only an intermediate for notarizing the .app before it went
# into the DMG — generate_appcast would otherwise see it as a duplicate of the
# same version and refuse to run.
# Filename is "browser-appcast.xml", not the generic "appcast.xml" — that name
# is already taken by another app's feed (Dictate) in the same downloads
# folder on nathanfennel.com. Must match SUFeedURL in Browser-Info.plist.
rm -f "$BUILD/Browser.zip"
./scripts/sparkle-bin/generate_appcast \
    --download-url-prefix "https://nathanfennel.com/downloads/" \
    --link "https://nathanfennel.com/internet" \
    -o "$BUILD/browser-appcast.xml" \
    "$BUILD"

echo "Ready to upload: $DMG and $BUILD/browser-appcast.xml"
