#!/bin/bash
#
# Builds, signs, notarizes, and staples a distributable Internet.dmg.
#
# One-time setup:
#   1. Create a "Developer ID Application" certificate:
#      Xcode -> Settings -> Accounts -> Manage Certificates -> + -> Developer ID Application
#   2. Store notarization credentials (app-specific password from account.apple.com):
#      xcrun notarytool store-credentials notary --apple-id nathanfennel@gmail.com --team-id EJLR2RPSV2
#
# Usage: ./scripts/release.sh          (override profile with NOTARY_PROFILE=name)
# Output: build/release/Internet.dmg — upload this to the website.

set -euo pipefail
cd "$(dirname "$0")/.."

PROJECT="Straight Up Browser.xcodeproj"
SCHEME="Browser"
PROFILE="${NOTARY_PROFILE:-notary}"
BUILD="build/release"

security find-identity -v -p codesigning | grep -q "Developer ID Application" || {
    echo "No 'Developer ID Application' certificate in the keychain."
    echo "Create one: Xcode -> Settings -> Accounts -> Manage Certificates -> + -> Developer ID Application"
    exit 1
}

# The scheme is Xcode-autogenerated (no shared .xcscheme on disk) - verify it resolves
xcodebuild -list -project "$PROJECT" 2>/dev/null | grep -q "^        $SCHEME\$" || {
    echo "Scheme '$SCHEME' not found. Open the project in Xcode once to autogenerate it."
    exit 1
}

rm -rf "$BUILD"
mkdir -p "$BUILD"

xcodebuild archive -project "$PROJECT" -scheme "$SCHEME" -configuration Release \
    -archivePath "$BUILD/Browser.xcarchive" -allowProvisioningUpdates

cat > "$BUILD/exportOptions.plist" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
    <key>method</key><string>developer-id</string>
    <key>teamID</key><string>EJLR2RPSV2</string>
    <key>signingStyle</key><string>automatic</string>
</dict></plist>
EOF

xcodebuild -exportArchive -archivePath "$BUILD/Browser.xcarchive" \
    -exportOptionsPlist "$BUILD/exportOptions.plist" -exportPath "$BUILD/export" \
    -allowProvisioningUpdates

STAGE="$BUILD/dmg"
DMG="$BUILD/Internet.dmg"
mkdir -p "$STAGE"
cp -R "$BUILD/export/Browser.app" "$STAGE/"
ln -s /Applications "$STAGE/Applications"

# Notarize and staple the app itself before it goes into the DMG, so a
# first launch works offline; the DMG gets its own ticket below.
ditto -c -k --keepParent "$STAGE/Browser.app" "$BUILD/Internet.zip"
xcrun notarytool submit "$BUILD/Internet.zip" --keychain-profile "$PROFILE" --wait
xcrun stapler staple "$STAGE/Browser.app"

hdiutil create -volname "Internet" -srcfolder "$STAGE" -ov -format UDZO "$DMG"

codesign --force --sign "Developer ID Application" "$DMG"
xcrun notarytool submit "$DMG" --keychain-profile "$PROFILE" --wait
xcrun stapler staple "$DMG"
spctl -a -t open --context context:primary-signature -v "$DMG"

echo "Ready to upload: $DMG"
